#!/usr/bin/env bash
# Installs and configure HAproxy on the lb-01 server
# using roundrobin algorithm

sudo apt-get update -y
sudo apt-get install haproxy -y

# Configure HAProxy using roundrobin algorithm
echo "
frontend http_front
        bind *:80
        default_backend http_back

backend http_back
        balance roundrobin
        server 111656-web-01 54.158.194.127:80 check
        server 111656-web-02 35.175.132.172:80 check
">> /etc/haproxy/haproxy.cfg

# Enable HAProxy
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

sudo service haproxy restart
